### ISSUE TITLE
HNET website crashed when loading BC2_WL website

### ISSUE THREAD

**Issue by dogunbound** [DataAnalyticsinStudentHands/HNETDataMaps#31]
https://hnet.uh.edu/bc2site/99996

Can access all other sites, just not BC2_WL. Please make sure it isn't a linux thing by going to the site on a non-linux machine (though I highly doubt it is a linux thing). The recent commit to back end may be the culprit.

It only happens when you load data for BC2. Don't think the site matters, just that there is BC2 data.

**Comment by peggylind** [comment]
this has been fixed with https://github.com/DataAnalyticsinStudentHands/HNETDataMaps/commit/1c23bd9353b777d53d0c28b63fed13ceabff6cda
